# Generated by Django 4.0.5 on 2022-07-02 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technologist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_over_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Technical_Task',
            fields=[
                ('tasks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisor.tasks')),
                ('comment', models.CharField(max_length=500, verbose_name='комментарий к заданию')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='technologist.defects')),
            ],
            bases=('supervisor.tasks',),
        ),
        migrations.CreateModel(
            name='Other_Task',
            fields=[
                ('tasks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervisor.tasks')),
                ('task_name', models.CharField(max_length=50, verbose_name='название')),
                ('comment', models.CharField(max_length=500, verbose_name='комментарий к заданию')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('planned_fix_it', models.DateTimeField()),
                ('factual_fix_it', models.DateTimeField()),
                ('check_it', models.BooleanField(default=False)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('supervisor.tasks',),
        ),
    ]
